#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  GeoShare — one-shot Firebase provisioning.
#
#  Automates everything that can be automated:
#    • installs firebase-tools (via npx)
#    • signs you in (one-time browser login)
#    • creates (or reuses) a Firebase project
#    • registers a Web app and writes its config into .env
#    • creates the Realtime Database instance
#    • deploys the security rules (database.rules.json)
#
#  The ONLY manual step left is a single console toggle:
#    Authentication → Sign-in method → Email/Password → Enable
#  (Auth providers cannot be toggled from the CLI.)
#
#  Usage:
#    npm run firebase:init                 # interactive, creates a new project
#    npm run firebase:init -- my-project   # use/create a specific project id
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail
cd "$(dirname "$0")/.."

FB="npx --yes firebase-tools"
PROJECT_ID="${1:-}"
REGION="${FIREBASE_RTDB_REGION:-us-central1}"

say()  { printf '\n\033[1;34m▸ %s\033[0m\n' "$1"; }
ok()   { printf '\033[1;32m✓ %s\033[0m\n' "$1"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$1"; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$1" >&2; exit 1; }

# 1. Auth ----------------------------------------------------------------------
say "Checking Firebase login…"
if ! $FB projects:list >/dev/null 2>&1; then
  warn "Not logged in. A browser window will open for a one-time login."
  $FB login || die "firebase login failed."
fi
ok "Authenticated."

# 2. Project -------------------------------------------------------------------
if [ -z "$PROJECT_ID" ]; then
  PROJECT_ID="geoshare-$(date +%s | tail -c 7)"
  say "Creating a new project: $PROJECT_ID"
  $FB projects:create "$PROJECT_ID" --display-name "GeoShare" \
    || die "Project creation failed (the id may already be taken — pass your own: npm run firebase:init -- your-id)."
else
  if $FB projects:list 2>/dev/null | grep -q "\b$PROJECT_ID\b"; then
    ok "Using existing project: $PROJECT_ID"
  else
    say "Creating project: $PROJECT_ID"
    $FB projects:create "$PROJECT_ID" --display-name "GeoShare" \
      || die "Project creation failed."
  fi
fi

# 3. Web app + SDK config ------------------------------------------------------
say "Registering a Web app…"
APP_ID="$(
  $FB apps:create web "GeoShare Web" --project "$PROJECT_ID" 2>/dev/null \
    | grep -oE 'App ID:[[:space:]]*[0-9a-zA-Z:_-]+' | awk '{print $NF}' | head -n1
)"
if [ -z "${APP_ID:-}" ]; then
  # Fall back to an already-registered web app.
  APP_ID="$($FB apps:list web --project "$PROJECT_ID" 2>/dev/null \
    | grep -oE '1:[0-9]+:web:[0-9a-f]+' | head -n1)"
fi
[ -n "${APP_ID:-}" ] || die "Could not create or find a Web app."
ok "Web app: $APP_ID"

# 4. Realtime Database instance ------------------------------------------------
say "Creating the Realtime Database instance…"
$FB database:instances:create "${PROJECT_ID}-default-rtdb" \
  --project "$PROJECT_ID" --location "$REGION" >/dev/null 2>&1 \
  && ok "RTDB instance ready." \
  || warn "RTDB instance may already exist (or needs creating once in the console → Realtime Database → Create). Continuing."

# 5. Write .env from the SDK config -------------------------------------------
say "Fetching SDK config and writing .env…"
CONFIG_JSON="$($FB apps:sdkconfig web "$APP_ID" --project "$PROJECT_ID" --json 2>/dev/null)"
[ -n "$CONFIG_JSON" ] || die "Could not read SDK config."

# Parse with node (config passed via env to avoid shell-quoting issues).
CONFIG_JSON="$CONFIG_JSON" PROJECT_ID="$PROJECT_ID" REGION="$REGION" node <<'NODE'
const fs = require('fs');
const cfgRaw = process.env.CONFIG_JSON;
const projectId = process.env.PROJECT_ID;
let c = {};
try {
  const parsed = JSON.parse(cfgRaw);
  c = parsed.result?.sdkConfig || parsed.sdkConfig || parsed.result || parsed;
} catch (e) {
  console.error('Failed to parse SDK config:', e.message);
  process.exit(1);
}
const databaseURL =
  c.databaseURL || `https://${projectId}-default-rtdb.${(process.env.REGION||'us-central1').includes('europe') ? 'europe-west1.firebasedatabase.app' : 'firebaseio.com'}`;

const lines = [
  '# Generated by scripts/firebase-init.sh',
  `EXPO_PUBLIC_FIREBASE_API_KEY=${c.apiKey || ''}`,
  `EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${c.authDomain || projectId + '.firebaseapp.com'}`,
  `EXPO_PUBLIC_FIREBASE_DATABASE_URL=${databaseURL}`,
  `EXPO_PUBLIC_FIREBASE_PROJECT_ID=${c.projectId || projectId}`,
  `EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${c.storageBucket || projectId + '.appspot.com'}`,
  `EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${c.messagingSenderId || ''}`,
  `EXPO_PUBLIC_FIREBASE_APP_ID=${c.appId || ''}`,
  '',
  '# Map uses OpenStreetMap — no key required.',
  'EAS_PROJECT_ID=',
  '',
].join('\n');

fs.writeFileSync('.env', lines);
console.log('✓ Wrote .env');
NODE
[ $? -eq 0 ] || die "Failed to write .env."

# 6. Deploy security rules -----------------------------------------------------
say "Deploying database security rules…"
$FB deploy --only database --project "$PROJECT_ID" \
  && ok "Rules deployed." \
  || warn "Rules deploy failed — if RTDB isn't created yet, create it in the console then run: npm run deploy:rules"

# 7. Final instructions --------------------------------------------------------
cat <<DONE

────────────────────────────────────────────────────────
✅ Firebase is configured. Project: $PROJECT_ID
   .env has been written with your Firebase credentials.

⚠️  ONE manual step remains (CLI cannot toggle auth providers):
   Firebase Console → Authentication → Sign-in method →
   Email/Password → Enable.
   https://console.firebase.google.com/project/$PROJECT_ID/authentication/providers

Then start the app:
   npx expo start
────────────────────────────────────────────────────────
DONE
